/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Canvas/index.vue')['default']
    Ccrape: typeof import('./src/components/Ccrape/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Hand: typeof import('./src/components/SmartVideo/hand.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scrape: typeof import('./src/components/scrape/index.vue')['default']
    SmartVideo: typeof import('./src/components/SmartVideo/index.vue')['default']
    StandardTable: typeof import('./src/components/StandardTable/index.vue')['default']
    Test: typeof import('./src/components/SmartVideo/test.vue')['default']
  }
}
