name: Deploy Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v3

      - name: Node环境
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装依赖
        run: npm install

      - name: 代码检查
        run: npm run lint

      - name: 打包
        run: npm run build

      # - name: 上传服务器
      #   uses: appleboy/scp-action@v0.1.3
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: root
      #     password: ${{ secrets.SERVER_PASSWORD }}
      #     source: "dist/*"
      #     target: "/var/www/project"